Repository KubenKoder/UtstyrKubenRobotikk, pull requests merged in 2019-08, with the labels that each got.

#2 Endre folder struktur og endre navn på filer
  README.md
  bilder/Verktøyliste_Robotikklinja_2019-2020.png
  dokumenter/Verktøyliste_Robotikklinja.xlsx
Labels: enhancement

#9 Bindestrek i UtstyrKubenRobotikk.md
  dokumenter/2ELR_Software.md
Labels: scope:documentation, type:fix

#10 Fusion 360 version Update
  dokumenter/2ELR_Software.md
Labels: scope:documentation, type:enhancement

#11 Create 1ELR_Software.md
  dokumenter/1ELR_Software.md
Labels: scope:documentation, type:enhancement

#13 Fiks markdown i Automasjons pensum
  dokumenter/2ELR_AutSys_Pensum_2019_2020.md
Labels: scope:documentation, type:fix

#19 Update 1ELR_Software.md
  dokumenter/1ELR_Software.md
  dokumenter/2ELR_Software.md
Labels: scope:documentation, type:invalid
